name: cogni_play
description: cogni_play game
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.28.0
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/Objects/anchor.png
    - assets/images/Objects/book.png
    - assets/images/Objects/bottle.png
    - assets/images/Objects/chalice.png
    - assets/images/Objects/coin.png
    - assets/images/Objects/diamond.png
    - assets/images/Objects/hook.png
    - assets/images/Objects/necklace.png
    - assets/images/Objects/rope.png
    - assets/images/Objects/treasure_map.png
    - assets/icons/settings.png
    - assets/icons/logo.png
    - assets/icons/profile.png
    - assets/icons/search.png
    - assets/icons/back.png
    - assets/level_data.json
    - assets/images/character.png
    - assets/images/ocean_level.png

dependency_overrides:
 material_color_utilities: ^0.12.0 